feat: cache Axiom SRS (trusted setup)
axiom-crypto/halo2-browser pull request #54
Opened 2024-01-15 15:10 UTC by jonathanpwang

I'm going to publish this under alpha version.

2024-01-15 15:17 UTC, jonathanpwang commented
Note: I don't know how this will work in browser.

2024-01-15 15:25 UTC, rpalakkal requested changes

2024-01-15 15:25 UTC, rpalakkal commented on halo2-wasm/js/kzg/index.ts
> +  const home = os.homedir();
I think just like `fetchAndConvertToUint8Array` we need to first check if this is running in Node.js or browser, and only use/import `os`/`path`/`https`  if it's node. And maybe we could save to localStorage if it's from browser?

2024-01-18 04:18 UTC, ytham commented
closing since we have merged this instead: https://github.com/axiom-crypto/halo2-browser/pull/55

2024-01-18 04:18 UTC, closed without merging